In [1]:
import torch

In [3]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
print("a:");
print(a)
print("b:");
print(b)

a:
tensor([[2, 1, 1],
        [2, 3, 2]])
b:
tensor([[3, 2, 3],
        [3, 3, 2]])


In [4]:
a + b

tensor([[5, 3, 4],
        [5, 6, 4]])

In [5]:
torch.add(a,b)

tensor([[5, 3, 4],
        [5, 6, 4]])

In [7]:
result = torch.zeros(2,3)
print("相加之前的result值:")
print(result)
torch.add(a,b,out=result)
print("相加之前的result值:")
print(result)

相加之前的result值:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
相加之前的result值:
tensor([[5., 3., 4.],
        [5., 6., 4.]])


In [8]:
result

tensor([[5., 3., 4.],
        [5., 6., 4.]])

In [9]:
# a = a + b
# 注意: 任何使张量tensor会发生变化的操作都有一个前缀‘_’,例如a.add_(),b.sub_()
a.add_(b)
a

tensor([[5, 3, 4],
        [5, 6, 4]])

In [10]:
a - b

tensor([[2, 1, 1],
        [2, 3, 2]])

In [11]:
a * b

tensor([[15,  6, 12],
        [15, 18,  8]])

In [12]:
print("a:");
print(a)
print("b:");
print(b)

a:
tensor([[5, 3, 4],
        [5, 6, 4]])
b:
tensor([[3, 2, 3],
        [3, 3, 2]])


In [13]:
a + b

tensor([[8, 5, 7],
        [8, 9, 6]])

In [14]:
a - b

tensor([[2, 1, 1],
        [2, 3, 2]])

In [15]:
a * b

tensor([[15,  6, 12],
        [15, 18,  8]])

In [16]:
a / b

tensor([[1.6667, 1.5000, 1.3333],
        [1.6667, 2.0000, 2.0000]])

In [17]:
# 取余数
a % b

tensor([[2, 1, 1],
        [2, 0, 0]])

In [18]:
# 取整
a // b

tensor([[1, 1, 1],
        [1, 2, 2]])

In [19]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [20]:
a

tensor([[5, 3, 4],
        [5, 6, 4]])

In [21]:
torch.matmul(a,tensor)

RuntimeError: expected scalar type Long but found Float

In [22]:
a.dtype

torch.int64

In [23]:
tensor.dtype

torch.float32

In [24]:
a = a.float()
a.dtype

torch.float32

In [25]:
torch.matmul(a,tensor)

tensor([[12., 12., 12., 12., 12.],
        [15., 15., 15., 15., 15.]])

In [26]:
a

tensor([[5., 3., 4.],
        [5., 6., 4.]])

In [27]:
a.T

tensor([[5., 5.],
        [3., 6.],
        [4., 4.]])