In [1]:
import torch

In [2]:
sample = torch.rand(3,2)

In [3]:
sample

tensor([[0.1266, 0.0797],
        [0.9438, 0.5129],
        [0.3543, 0.5668]])

In [4]:
torch.sum(sample)

tensor(2.5841)

In [7]:
sample[0,0].item()

0.1265507936477661

In [8]:
sample[0,1].item()

0.07972681522369385

In [9]:
sample[1,0].item()

0.9437570571899414

In [11]:
tempSum = sample[0,0].item()+sample[0,1].item()+sample[1,0].item()+sample[1,1].item()+sample[2,0].item()+sample[2,0].item()
print("tempSum: ")
tempSum

tempSum: 


2.3716278076171875

In [12]:
torch.max(sample)

tensor(0.9438)

In [14]:
# 求最小值所在的位置（索引）
torch.argmin(sample)

tensor(1)

In [15]:
# 求最大值所在的位置（索引）
torch.argmax(sample)

tensor(2)

In [16]:
# 求均值
torch.mean(sample)

tensor(0.4307)

In [17]:
# 求中位数
torch.median(sample)

tensor(0.3543)

In [18]:
# 求平方
torch.sqrt(sample)

tensor([[0.3557, 0.2824],
        [0.9715, 0.7162],
        [0.5953, 0.7529]])

In [21]:
# 求2次方
sample ** 2

tensor([[0.0160, 0.0064],
        [0.8907, 0.2631],
        [0.1256, 0.3213]])