In [1]:
import torch

In [2]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(3,4)

tensor([[0.8485, 0.1690, 0.2522, 0.2665],
        [0.5425, 0.1519, 0.8554, 0.7956],
        [0.2260, 0.6229, 0.9412, 0.8002]])

In [5]:
torch.randint(0,10,(2,3))

tensor([[0, 3, 0],
        [6, 5, 9]])

In [6]:
# 生成正太分布的随机数
torch.randn(3,4)

tensor([[-0.5261,  1.1272, -1.9987,  0.7521],
        [-0.9335, -0.1600, -0.0916,  0.2663],
        [-0.4616,  1.5079,  0.1564,  0.1900]])

In [7]:
a = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

In [8]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
b = torch.rand_like(a, dtype=float)
b

tensor([[0.8961, 0.7792],
        [0.8033, 0.9162],
        [0.4702, 0.9805]], dtype=torch.float64)

In [10]:
# 查看数据的形状
print(b.shape)
print(b.size())

torch.Size([3, 2])
torch.Size([3, 2])


In [14]:
# view相当于reshape
c = b.view(6)
c

tensor([0.8961, 0.7792, 0.8033, 0.9162, 0.4702, 0.9805], dtype=torch.float64)

In [15]:
b

tensor([[0.8961, 0.7792],
        [0.8033, 0.9162],
        [0.4702, 0.9805]], dtype=torch.float64)

In [16]:
c.shape

torch.Size([6])

In [17]:
d = b.view(2,3)
d

tensor([[0.8961, 0.7792, 0.8033],
        [0.9162, 0.4702, 0.9805]], dtype=torch.float64)

In [18]:
d = d.reshape(6)
d

tensor([0.8961, 0.7792, 0.8033, 0.9162, 0.4702, 0.9805], dtype=torch.float64)

In [19]:
d[1]

tensor(0.7792, dtype=torch.float64)

In [21]:
# 获取数值变成python环境中的标准数据类型
d[1].item()

0.7791711774180413

In [23]:
# .item()只能修改一个值
d.item() 

ValueError: only one element tensors can be converted to Python scalars

In [24]:
import numpy as np

In [25]:
np.array(d)

array([0.89607225, 0.77917118, 0.80327413, 0.9161576 , 0.47016177,
       0.98045765])

In [27]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [30]:
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3])

In [31]:
tensor.dtype()

TypeError: 'torch.dtype' object is not callable

In [32]:
tensor.dtype

torch.int64